### ISSUE TITLE
crash 4.3.1

### ISSUE THREAD

**Issue by dklt** [criteo/ios-publisher-sdk#212]
CR_InternalContextProvider.m - Line 93
-[CR_InternalContextProvider fetchDeviceConnectionType] + 93 

probable causes + likely fix:  5G detect version-lock to 14.1+

ref: https://stackoverflow.com/questions/63771488/how-to-detect-the-5gnr-on-ios14
ref2: details in the comment

will crash on 14.0, 14.0.1, easily repeatable

~ cheers

**Comment by TurpIF** [comment]
Thank you for the report.
This issue should be fixed by this commit: https://github.com/criteo/ios-publisher-sdk/commit/20d4ce55c8990b461386638fd622234e663972d2
It is not yet released as a version, but we will publish a new one soon.

**Comment by vguerci** [comment]
4.3.2 Just got released and should fix this issue.
Sorry for the inconvenience and feel free to reopen if that is not the case.
