### ISSUE TITLE
[GoogleAdmob Adapter] Renamig kGADError* to GADError* breaks with GoogleAdmob v7.69

### ISSUE THREAD

**Issue by Khronoss** [criteo/ios-publisher-sdk#214]
Hi,

I added your adapter using cocoapods in my projet
I have `Google-Mobile-Ads v7.69.0` and added `CriteoPublisherSdk/GoogleAdapter v4.3.2` but the compiler complained that in the file `CRGoogleMediationParameters.m` the `GADErrorDomain` and `GADErrorInvalidArgument` weren't declared and maybe I tried using `kGADErrorDomain` and `kGADErrorInvalidArgument` instead.

I checked the GoogleAdmob's reference and they were there so it wasn't any kind of mistake from you so I thougth it was an addition that weren't available in my version of the GoogleAdmob SDK

So I changed the Criteo's SDK version to 4.3.1 and the error was still there. So I lowered it again, to 4.3.0, and compilation succeed, Hooray!

My guess is that the GoogleAdmob naming change occured on the v8 which would make the use of Criteo v4.3.1 and later impossible with GoogleAdmob less than v8 but your podspec doesn't reflect this restriction

I'm not sure about my conclusion because Google doesn't make easy to see _when_ they made this change, maybe you'll have a better knowledge about it

Thanks!
Bilkix

**Comment by vguerci** [comment]
Hello, yes you are right about concluding that this is due to latest AdMob changes, which unfortunately weren't reflected in the podspec. We'll fix pod spec, and maybe consider another fix to support older AdMob versions.

Just curious, Is there anything preventing you to upgrade AdMob SDK?

**Comment by Khronoss** [comment]
Hi! Thank you for your quick answer 👍 

I don't have any (purely) technical reasons to not upgrade into Admob v8. It's mostly because I'm integrating ads into a new app of my organisation, I never done that before, and our internal tools are currently designed to run with Admob v7.x
I plan to upgrade to v8 as soon as I could, but for now I though it would be easier for me to not add this complexity as I'm still learning how our internal tools work (tl;dr: I'm a dead ass newbie on this subject 😂 )

**Comment by vguerci** [comment]
No problem, thanks for your answer, 4.3.3 has just been released with the fix above #216.

Thanks for your report and sorry for the inconvenience.

**Comment by Khronoss** [comment]
No problem, the workaround was easy (just using 4.3.0, which is not realy _outdated_ I would say)
Thank you and kudos for great support 👍
