### ISSUE TITLE
Support to XCFramework

### ISSUE THREAD

**Issue by DrAma999** [criteo/ios-publisher-sdk#223]
Hello there,
are you planning to support xcframework releases?
Mostly due to manual integration for users with M1 mac

**Comment by vguerci** [comment]
Hello,

We encourage integration through CocoaPods, as it has benefits such as building from source, which should solve M1 / arm64 issues.
But as we also provide framework [releases](https://github.com/criteo/ios-publisher-sdk/releases), we are considering switching them to xcframework.

**Comment by DrAma999** [comment]
I saw and yes it solves the issue, but Cocoapods is quite intrusive as a dependency manager and, so far, it seems the only option (along with manual) to integrate your library. There is no trace of Swift Package Manager or carthage.
Manual is totally fine and would be suitable for my specifications but not usable due to missing iOS simulator architecture.
Best,
Andrea

**Comment by vguerci** [comment]
Hello,

Worked on #225, could you please confirm me that [this packaging](https://github.com/criteo/ios-publisher-sdk/releases/download/4.4.0-xcframework1) works on your side?

**Comment by DrAma999** [comment]
Wow, thank you so much...we are in the middle of a sprint at the moment. I will try to arrange next week

**Comment by vguerci** [comment]
Hello @DrAma999 by any chance, did you find some time to test this?
We will merge this and planning to release a new version with it.

**Comment by DrAma999** [comment]
@vguerci still not... I'm very sorry but it is a hard time. If you want to close the issue I understand, eventually I will reopen it when I had time to test them.

**Comment by vguerci** [comment]
No problem, the related change has been merged and the upcoming 4.4 version will be packaged as a XCFramework.
Feel free to reopen this or another issue if needed.
